/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import controller.AntrianController;
import model.Antrian;
/**
 *
 * @author LENOVO
 */
public class AntrianForm extends javax.swing.JFrame {
    String idAntrian;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AntrianForm.class.getName());

    /**
     * Creates new form AntrianForm
     */
    public AntrianForm() {
        initComponents();
        nomorAntrian();
        setLocationRelativeTo(null);
        tampilAntrian();
        tampilPasien();
        
    }
private void nomorAntrian() {

    try {

        Connection conn = Koneksi.getKoneksi();

        Statement st = conn.createStatement();

        ResultSet rs = st.executeQuery("SELECT * FROM antrian ORDER BY id_antrian DESC");

        if (rs.next()) {

            int nomor = rs.getInt("id_antrian") + 1;

            txtNomor.setText("A" + nomor);

        } else {

            txtNomor.setText("A1");

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e.getMessage());

    }

}

private void tampilAntrian() {

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("NO ANTRIAN");
    model.addColumn("NAMA");
    model.addColumn("POLI");
    model.addColumn("STATUS");

    try {

        Connection conn = Koneksi.getKoneksi();

        Statement st = conn.createStatement();

        ResultSet rs = st.executeQuery(
    "SELECT antrian.*, pasien.nama " +
    "FROM antrian " +
    "JOIN pasien " +
    "ON antrian.id_pasien = pasien.id_pasien"
);

        while (rs.next()) {

            model.addRow(new Object[] {

        rs.getString("id_antrian"),
        rs.getString("nomor_antrian"),
        rs.getString("nama"),
        rs.getString("poli"),
        rs.getString("status")

            });

        }

        tableAntrian.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e.getMessage());

    }

}

private void tampilPasien() {

    try {

        Connection conn = Koneksi.getKoneksi();

        Statement st = conn.createStatement();

        ResultSet rs = st.executeQuery("SELECT * FROM pasien");

        while (rs.next()) {

            cbPasien.addItem(
                    rs.getString("id_pasien") +
                    " - " +
                    rs.getString("nama")
            );

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e.getMessage());

    }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomor = new javax.swing.JTextField();
        cbPoli = new javax.swing.JComboBox<>();
        cbStatus = new javax.swing.JComboBox<>();
        btnAmbil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAntrian = new javax.swing.JTable();
        btnPanggil = new javax.swing.JButton();
        btnSelesai = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        cbPasien = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNomor.addActionListener(this::txtNomorActionPerformed);

        cbPoli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Umum", "Gigi", "Anak", "Mata" }));
        cbPoli.setToolTipText("");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menunggu", "Dipanggil", "Selesai" }));

        btnAmbil.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        btnAmbil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/hand.png"))); // NOI18N
        btnAmbil.setText("AMBIL ANTRIAN");
        btnAmbil.addActionListener(this::btnAmbilActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel1.setText("NO");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel2.setText("NAMA");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel3.setText("POLI");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel4.setText("STATUS");

        tableAntrian.setBackground(new java.awt.Color(51, 204, 255));
        tableAntrian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Poli", "Status"
            }
        ));
        tableAntrian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAntrianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAntrian);

        btnPanggil.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        btnPanggil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/phone-call.png"))); // NOI18N
        btnPanggil.setText("PANGGIL");
        btnPanggil.addActionListener(this::btnPanggilActionPerformed);

        btnSelesai.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        btnSelesai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/save.png"))); // NOI18N
        btnSelesai.setText("SELESAI");
        btnSelesai.addActionListener(this::btnSelesaiActionPerformed);

        btnKembali.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/logout.png"))); // NOI18N
        btnKembali.setText("KEMBALI");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomor)
                    .addComponent(cbPasien, 0, 118, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbPoli, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSelesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAmbil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPanggil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnAmbil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnPanggil)
                    .addComponent(cbPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelesai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKembali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAmbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmbilActionPerformed
      String pasien = cbPasien.getSelectedItem().toString();

String idPasien = pasien.split(" - ")[0];

Antrian antrian = new Antrian(

    txtNomor.getText(),
    idPasien,
    cbPoli.getSelectedItem().toString(),
    cbStatus.getSelectedItem().toString()

);

AntrianController controller = new AntrianController();

controller.simpan(antrian);

nomorAntrian();
tampilAntrian();
    }//GEN-LAST:event_btnAmbilActionPerformed

    private void txtNomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomorActionPerformed

    private void tableAntrianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAntrianMouseClicked
        int baris = tableAntrian.rowAtPoint(evt.getPoint());

     idAntrian = tableAntrian.getValueAt(baris, 0).toString();


    }//GEN-LAST:event_tableAntrianMouseClicked

    private void btnPanggilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanggilActionPerformed
    AntrianController controller = new AntrianController();

    controller.panggil(idAntrian);

    tampilAntrian();
    }//GEN-LAST:event_btnPanggilActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
    AntrianController controller = new AntrianController();

    controller.selesai(idAntrian);

    tampilAntrian();


    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
       new DashboardForm().setVisible(true);

       dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AntrianForm().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmbil;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnPanggil;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JComboBox<String> cbPasien;
    private javax.swing.JComboBox<String> cbPoli;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAntrian;
    private javax.swing.JTextField txtNomor;
    // End of variables declaration//GEN-END:variables
}
